export const BASE_URL = "http://localhost:8000"
// export const BASE_URL = "http://130.185.78.233:8000"
export const UPDATE_CARDS = "UPDATE_CARDS"
export const UPDATE_CONFIGS = "UPDATE_CONFIGS"
export const UPDATE_TOP_SALE= "UPDATE_TOP_SALE"
export const UPDATE_BRANDS = "UPDATE_BRANDS"
export const UPDATE_COUNTRIES = "UPDATE_COUNTRIES"
export const UPDATE_FETCHING_BRANDS = "UPDATE_FETCHING_BRANDS"
export const UPDATE_FETCHING_CARDS = "UPDATE_FETCHING_CARDS"
export const UPDATE_FETCHING_COUNTRIES = "UPDATE_FETCHING_COUNTRIES"


export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_STATUS = "UPDATE_STATUS"


export const UPDATE_BASKET = "UPDATE_BASKET"
export const SET_CART = "SET_CART"

export const UPDATE_LOGIN_MODAL = "UPDATE_LOGIN_MODAL"
